### ISSUE TITLE
TCC dataset couldn't download

### ISSUE THREAD

**Issue by DavideHe** [yanlinqian/Temporal-Color-Constancy#1]
I want to download your benchmark dataset for research,but i find the link invalid.
Could you add a valid link for downloading ?
Thanks very much !!

**Comment by yanlinqian** [comment]
Please check this link, https://www.cs.ubc.ca/research/tcc/.

**Comment by DavideHe** [comment]
> Please check this link, https://www.cs.ubc.ca/research/tcc/.

Thanks very much !!
