### ISSUE TITLE
How to obtain the GT vector when you collected the datasets?

### ISSUE THREAD

**Issue by Zwette** [yanlinqian/Temporal-Color-Constancy#5]
Thanks for your awesome work. I am wondering how the vector in the groundtruth.txt is obtained? Could you please present a detailed explanation on it?

**Comment by yanlinqian** [comment]
aha, this is straight forward and easy to find some doc, for example this paper "[Illumination Estimation Challenge: experience of past two years](https://arxiv.org/abs/2012.15779)"
